steps:
  # Step 1: Install dependencies
  - name: 'python:3.13'
    id: 'Install dependencies'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  # Step 2: Build and push Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image to GCR'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flask-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flask-app'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Remove if authentication is required

images:
  - 'gcr.io/$PROJECT_ID/flask-app'
